# url: https://y7kim.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: 政治公園
email: boojoe.nctu@gmail.com
description:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: 陳正和
  pic: 1
  position: Lead Designer
  social:
    - title: facebook
      url: #

- name: 黃榆鈞
  pic: 2
  position: Lead Marketer
  social:
    - title: facebook
      url: #

- name: 張育瑄
  pic: 3
  position: Lead Developer
  social:
    - title: facebook
      url: #
    - title: github
      url: #
    - title: stack-overflow
      url: #

- name: 陳韋廷
  pic: 4
  position: Lead Developer
  social:
    - title: facebook
      url: #
    - title: github
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:
  - title: github
    url: https://github.com/boojoe/political-party

# Postal address (add as many lines as necessary)
address:
  - line: 新竹市東區1001號 國立交通大學

# Build settings
markdown: kramdown
permalink: pretty
